[tox]
envlist =
    check
    docs
    nightlies
    {py312,py313,py314}{,-coverage}
# See https://tox.readthedocs.io/en/latest/example/package.html#flit
isolated_build = True
isolated_build_env = build
labels =
    dev = check, cleandocs, docs, livedocs, viewdocs, py312, py313, py314, nightlies

[gh-actions]
python =
    3.12: py312-coverage
    3.13: py313-coverage, check, nightlies
    3.14: py314-coverage

[testenv]
description = Run ArviZ-base tests
basepython =
    py312: python3.12
    py313: python3.13
    py314: python3.14
    # See https://github.com/tox-dev/tox/issues/1548
    {check,docs,cleandocs,viewdocs,build,nightlies}: python3
setenv =
    PYTHONUNBUFFERED = yes
    PYTEST_EXTRA_ARGS = -s
    coverage: PYTEST_EXTRA_ARGS = --cov --cov-report xml --cov-report term
passenv =
    *
extras =
    test
    netcdf4
commands =
    pytest {env:PYTEST_MARKERS:} {env:PYTEST_EXTRA_ARGS:} {posargs:}

[testenv:nightlies]
description = Run test job with nightly pre-releases of scientific python packages
install_command = python -I -m pip install --extra-index-url https://pypi.anaconda.org/scientific-python-nightly-wheels/simple {opts} {packages}
pip_pre = true
setenv =
  NIGHTLIES=TRUE
  PYTEST_EXTRA_ARGS = -W "ignore:Using 'generic' unit for NumPy timedelta:DeprecationWarning"

[testenv:check]
description = Perform style checks
extras =
    check
allowlist_externals =
    pre-commit
commands =
    pre-commit install
    pre-commit run --all-files --show-diff-on-failure --hook-stage manual
    python -m build

[testenv:docs]
description = Build HTML docs
setenv =
    READTHEDOCS_PROJECT = arviz_base
    READTHEDOCS_VERSION = latest
extras =
    doc
commands =
    sphinx-build -d "{toxworkdir}/docs_doctree" docs/source "{toxworkdir}/docs_out" --color -v -bhtml

[testenv:livedocs]
description = Build live preview of HTML docs with automatic updates
base = docs
extras =
    doc
    sphinx-autobuild
commands =
    sphinx-autobuild -d "{toxworkdir}/docs_doctree" docs/source "{toxworkdir}/docs_out" --color -v -bhtml

[testenv:cleandocs]
description = Clean HTML doc build outputs
skip_install = true
allowlist_externals = rm
commands =
    rm -r "{toxworkdir}/docs_out" "{toxworkdir}/docs_doctree" "{toxworkdir}/jupyter_execute" docs/source/api/generated docs/source/contributing/generated

[testenv:viewdocs]
description = View HTML docs with the default browser
skip_install = true
commands =
    python -m webbrowser "{toxworkdir}/docs_out/index.html"
